### ISSUE TITLE
Worldserver crash

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#258]
<a href="https://github.com/Nolin7777"><img src="https://avatars2.githubusercontent.com/u/20132236?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Nolin7777](https://github.com/Nolin7777)**
_Sunday Dec 09, 2018 at 08:06 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/25_

----

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by ./worldserver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ThreatManager::CanHaveThreatList (this=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Combat/ThreatManager.h:91
91              bool CanHaveThreatList() const { return _ownerCanHaveThreatList; }
[Current thread is 1 (Thread 0x7f21c6e62700 (LWP 30597))]
(gdb) bt
#0  ThreatManager::CanHaveThreatList (this=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Combat/ThreatManager.h:91
#1  Unit::CanHaveThreatList (this=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Entities/Unit/Unit.h:1106
#2  Unit::IsEngaged (this=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Entities/Unit/Unit.h:1110
#3  Spell::DoEffectOnLaunchTarget (this=0x7f21b663fde0, targetInfo=..., multiplier=1, effIndex=0 '\000') at /home/tbc/sunstrider-core/src/server/game/Spells/Spell.cpp:7945
#4  0x0000000000dd68a0 in Spell::HandleLaunchPhase (this=0x7f21b663fde0) at /home/tbc/sunstrider-core/src/server/game/Spells/Spell.cpp:7925
#5  0x0000000000dd5237 in Spell::_cast (this=0x7f21b663fde0, skipCheck=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Spells/Spell.cpp:3745
#6  0x0000000000dddf5e in SpellEvent::Execute (this=0x7f21b665d4b0, e_time=43557, p_time=3059879856) at /home/tbc/sunstrider-core/src/server/game/Spells/Spell.cpp:7754
#7  0x00000000011cee48 in EventProcessor::Update (this=0x7f21ba253220, p_time=99) at /home/tbc/sunstrider-core/src/common/Utilities/EventProcessor.cpp:46
#8  0x0000000000b18df5 in Unit::Update (this=0x7f21ba253100, p_time=99) at /home/tbc/sunstrider-core/src/server/game/Entities/Unit/Unit.cpp:408
#9  0x0000000000a1eead in Creature::Update (this=0x7f21ba253100, diff=99) at /home/tbc/sunstrider-core/src/server/game/Entities/Creature/Creature.cpp:782
#10 0x0000000000a447cf in TempSummon::Update (this=0x7f21ba253100, diff=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Entities/Creature/TemporarySummon.cpp:135
#11 0x0000000000ca56f3 in Trinity::ObjectUpdater::Visit (this=0x7f21c6e61d60, m=...) at /home/tbc/sunstrider-core/src/server/game/GridNotifiersImpl.h:36
#12 VisitorHelper<Trinity::ObjectUpdater, Creature> (v=..., c=...) at /home/tbc/sunstrider-core/src/server/shared/Dynamic/TypeContainerVisitor.h:28
#13 VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (v=..., c=...) at /home/tbc/sunstrider-core/src/server/shared/Dynamic/TypeContainerVisitor.h:34
#14 VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > (v=..., c=...) at /home/tbc/sunstrider-core/src/server/shared/Dynamic/TypeContainerVisitor.h:35
#15 VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (v=..., c=...) at /home/tbc/sunstrider-core/src/server/shared/Dynamic/TypeContainerVisitor.h:41
#16 TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >::Visit (this=<optimized out>, c=...)
    at /home/tbc/sunstrider-core/src/server/shared/Dynamic/TypeContainerVisitor.h:75
#17 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > >, Trinity::SingleThreaded<Player> >::Visit<Trinity::ObjectUpdater> (visitor=..., this=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Grids/Grid.h:74
#18 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > >, Trinity::SingleThreaded<Player> >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (this=<optimized out>, x=3, y=<optimized out>, visitor=...)
    at /home/tbc/sunstrider-core/src/server/game/Grids/NGrid.h:155
#19 Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > > (this=<optimized out>, cell=..., visitor=...)
    at /home/tbc/sunstrider-core/src/server/game/Maps/Map.h:912
#20 0x0000000000c8ac96 in Map::VisitNearbyCellsOf (this=0x1739d280, obj=<optimized out>, gridVisitor=..., worldVisitor=...) at /home/tbc/sunstrider-core/src/server/game/Maps/Map.cpp:795
#21 0x0000000000c8b1e0 in Map::Update (this=0x1739d280, t_diff=@0x7f21c6e61dfc: 99) at /home/tbc/sunstrider-core/src/server/game/Maps/Map.cpp:879
#22 0x0000000000c8ae0a in Map::DoUpdate (this=0x1739d280, maxDiff=100, minimumTimeSinceLastUpdate=<optimized out>) at /home/tbc/sunstrider-core/src/server/game/Maps/Map.cpp:813
#23 0x0000000000cbc99b in MapUpdateRequest::call (this=0x2dc13ac0) at /home/tbc/sunstrider-core/src/server/game/Maps/MapUpdater.cpp:37
#24 0x0000000000cbc329 in MapUpdater::OnceWorkerThread (this=0x1a3c010 <MapManager::instance()::instance+168>) at /home/tbc/sunstrider-core/src/server/game/Maps/MapUpdater.cpp:181
#25 0x00007f21e3c4ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#26 0x00007f21e473b494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#27 0x00007f21e33c1acf in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 08:08 GMT_

----

Ah yes, new crash because of ba2479c64c9e2866e02b9689e1ea18d92cdf628f, my bad!

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 08:09 GMT_

----

Should be fixed with last commit

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 10:02 GMT_

----

https://github.com/ValorenWoW/sunstrider-core/commit/454e378b99a1311ec661705867fe1b525a50d756
